/**
 * 25 Slide Archetypes — each defines:
 *   id:          unique key (matches audience-defaults entries)
 *   label:       human-readable slide title
 *   intent:      what this slide must accomplish
 *   atomQuery:   9D filters to pull relevant atoms from the payload
 *   promptHint:  guidance passed to the synthesizer LLM
 *   minAtoms:    minimum atoms needed (0 = no atoms required, e.g. title)
 */

const ARCHETYPES = [
  {
    id: 'title',
    label: 'Title Slide',
    intent: 'Set the stage — solution name, audience, seller branding',
    atomQuery: {},
    promptHint: 'Generate a compelling title and subtitle. Mention the solution name and the value proposition in 1 sentence.',
    minAtoms: 0,
  },
  {
    id: 'agenda',
    label: 'Agenda',
    intent: 'Preview the deck structure so the audience knows what to expect',
    atomQuery: {},
    promptHint: 'List the upcoming sections as short agenda bullet items (6-10 items). Keep each item to 4-8 words.',
    minAtoms: 0,
  },
  {
    id: 'market_opportunity',
    label: 'Market Opportunity',
    intent: 'Show the size and urgency of the market the solution addresses',
    atomQuery: { evidence_type: ['statistic', 'market_data'], buying_stage: ['awareness'] },
    promptHint: 'Lead with a market-size number or growth stat. Frame the opportunity window. Use 2-3 atoms as data points.',
    minAtoms: 2,
  },
  {
    id: 'client_demand',
    label: 'Client Demand',
    intent: 'Prove that end-customers are actively asking for this solution',
    atomQuery: { evidence_type: ['statistic', 'case_study', 'quote'], buying_stage: ['awareness', 'consideration'] },
    promptHint: 'Surface demand signals — survey results, deal-win quotes, support ticket trends. Make it feel urgent.',
    minAtoms: 2,
  },
  {
    id: 'pain_points_reflected',
    label: 'Pain Points',
    intent: 'Mirror the audience\'s problems back to them so they feel understood',
    atomQuery: { emotional_driver: ['fear', 'frustration', 'uncertainty'], buying_stage: ['awareness', 'consideration'] },
    promptHint: 'Frame 3-5 pain points the audience personally feels. Use their language, not vendor language. End with an empathetic bridge to the solution.',
    minAtoms: 2,
  },
  {
    id: 'threat_landscape',
    label: 'Threat Landscape',
    intent: 'Establish the current risk environment that makes action necessary',
    atomQuery: { evidence_type: ['statistic', 'market_data'], status_quo_pressure: ['high', 'critical'] },
    promptHint: 'Present recent threat stats and trends. Make inaction feel dangerous. 3-4 data points max.',
    minAtoms: 2,
  },
  {
    id: 'product_overview',
    label: 'Product Overview',
    intent: 'High-level what-it-is and why-it-matters',
    atomQuery: { evidence_type: ['feature', 'benefit'], buying_stage: ['consideration'] },
    promptHint: 'Explain what the solution does in 2-3 sentences, then list 4-6 key capabilities as short bullets. No jargon.',
    minAtoms: 3,
  },
  {
    id: 'product_deep_dive',
    label: 'Product Deep Dive',
    intent: 'Technical detail for evaluators who need to understand how it works',
    atomQuery: { evidence_type: ['feature', 'technical'], persona: ['technical', 'evaluator'] },
    promptHint: 'Go deeper on architecture, integrations, and differentiating features. Use 4-6 atoms. Be specific but accessible.',
    minAtoms: 3,
  },
  {
    id: 'competitive_comparison',
    label: 'Competitive Comparison',
    intent: 'Position the solution against alternatives without mud-slinging',
    atomQuery: { evidence_type: ['comparison', 'differentiator', 'feature'] },
    promptHint: 'Create a comparison table or point-by-point contrast. Highlight unique differentiators. Stay factual, let the data win.',
    minAtoms: 2,
  },
  {
    id: 'revenue_model',
    label: 'Revenue Model',
    intent: 'Show partners how they make money with this solution',
    atomQuery: { economic_driver: ['margin', 'recurring_revenue', 'deal_size'], persona: ['partner'] },
    promptHint: 'Break down the economics: margins, deal sizes, recurring vs. one-time. Show a sample deal calculation if possible.',
    minAtoms: 2,
  },
  {
    id: 'retention_play',
    label: 'Retention Play',
    intent: 'Demonstrate how this solution keeps customers sticky',
    atomQuery: { economic_driver: ['retention', 'recurring_revenue'], evidence_type: ['statistic', 'case_study'] },
    promptHint: 'Show renewal rates, churn reduction, or stickiness metrics. Frame the solution as a retention engine.',
    minAtoms: 1,
  },
  {
    id: 'sales_playbook',
    label: 'Sales Playbook',
    intent: 'Give partners/reps a repeatable sales motion',
    atomQuery: { persona: ['partner', 'sales'], buying_stage: ['consideration', 'decision'] },
    promptHint: 'Outline the ideal sales motion: discovery questions, demo flow, objection handling hooks. Keep it actionable.',
    minAtoms: 2,
  },
  {
    id: 'partner_tracks',
    label: 'Partner Tracks',
    intent: 'Outline the partner program tiers and benefits',
    atomQuery: { persona: ['partner'], evidence_type: ['program', 'benefit'] },
    promptHint: 'Present 2-4 partner tiers with clear benefits at each level. Show the growth path.',
    minAtoms: 1,
  },
  {
    id: 'distributor_value',
    label: 'Distributor Value',
    intent: 'Explain the distributor\'s role and value-add in the channel',
    atomQuery: { persona: ['partner', 'distributor'] },
    promptHint: 'Articulate what the distributor brings: billing, support, enablement, deal reg. Be specific to the program.',
    minAtoms: 1,
  },
  {
    id: 'onboarding_timeline',
    label: 'Onboarding Timeline',
    intent: 'Show how fast the audience can get started',
    atomQuery: { buying_stage: ['decision', 'onboarding'], evidence_type: ['process', 'timeline'] },
    promptHint: 'Present a 30/60/90 day or phased timeline. Include key milestones and expected outcomes at each phase.',
    minAtoms: 1,
  },
  {
    id: 'objection_handling',
    label: 'Objection Handling',
    intent: 'Pre-empt the top objections the audience will raise',
    atomQuery: { buying_stage: ['consideration', 'decision'], emotional_driver: ['skepticism', 'uncertainty'] },
    promptHint: 'List 4-6 common objections with crisp, evidence-backed responses. Format as Objection → Response pairs.',
    minAtoms: 2,
  },
  {
    id: 'proof_points',
    label: 'Proof Points',
    intent: 'Provide social proof — logos, metrics, testimonials',
    atomQuery: { evidence_type: ['case_study', 'testimonial', 'statistic'], credibility: [4, 5] },
    promptHint: 'Lead with the strongest metric or quote. Include 2-4 proof points. Name names when possible (logos, companies, roles).',
    minAtoms: 2,
  },
  {
    id: 'cta',
    label: 'Call to Action',
    intent: 'Drive the next step — clear, specific, time-bound',
    atomQuery: { buying_stage: ['decision'] },
    promptHint: 'One primary CTA, one secondary. Include contact info placeholder. Make the next step obvious and easy.',
    minAtoms: 0,
  },
  {
    id: 'appendix',
    label: 'Appendix',
    intent: 'Parking lot for extra data that supports the narrative',
    atomQuery: {},
    promptHint: 'Organize leftover high-value atoms by theme. Label each section clearly. This is reference material.',
    minAtoms: 0,
  },
  {
    id: 'compliance_mapping',
    label: 'Compliance Mapping',
    intent: 'Map the solution to regulatory and compliance frameworks',
    atomQuery: { evidence_type: ['compliance', 'certification', 'regulatory'] },
    promptHint: 'Show which frameworks the solution addresses (SOC2, HIPAA, NIST, etc.) with specific control mappings.',
    minAtoms: 1,
  },
  {
    id: 'bundling_strategy',
    label: 'Bundling Strategy',
    intent: 'Show partners how to bundle this with other solutions for larger deals',
    atomQuery: { persona: ['partner'], economic_driver: ['deal_size', 'margin'] },
    promptHint: 'Present 2-3 bundle configurations with expected deal sizes. Show the "better together" story.',
    minAtoms: 1,
  },
  {
    id: 'enterprise_readiness',
    label: 'Enterprise Readiness',
    intent: 'Prove the solution meets enterprise requirements',
    atomQuery: { evidence_type: ['feature', 'technical', 'compliance'], persona: ['technical', 'enterprise'] },
    promptHint: 'Cover SSO, RBAC, audit logs, SLAs, uptime, scale metrics. Checklist format works well.',
    minAtoms: 2,
  },
  {
    id: 'attach_playbook',
    label: 'Attach Playbook',
    intent: 'Show VARs how to attach this solution to existing deals',
    atomQuery: { persona: ['partner'], buying_stage: ['consideration'] },
    promptHint: 'Identify 3-5 trigger events or existing products where this solution attaches naturally. Give talk-track snippets.',
    minAtoms: 1,
  },
  {
    id: 'roi_calculator',
    label: 'ROI Calculator',
    intent: 'Quantify the financial return of adopting the solution',
    atomQuery: { evidence_type: ['statistic', 'case_study'], economic_driver: ['cost_savings', 'roi'] },
    promptHint: 'Build a simple ROI model: cost of inaction vs. cost of solution. Use real numbers from atoms. Show 1-year and 3-year returns.',
    minAtoms: 2,
  },
  {
    id: 'use_cases',
    label: 'Use Cases',
    intent: 'Show concrete scenarios where the solution delivers value',
    atomQuery: { evidence_type: ['case_study', 'scenario'], buying_stage: ['consideration'] },
    promptHint: 'Present 3-4 use cases with Situation → Solution → Result format. Keep each to 2-3 sentences.',
    minAtoms: 2,
  },
];

const ARCHETYPE_MAP = Object.fromEntries(ARCHETYPES.map(a => [a.id, a]));

module.exports = { ARCHETYPES, ARCHETYPE_MAP };
